FROM alpine:3.18

# Installing required packages
RUN apk add --update --no-cache \
    gcc libc-dev libffi-dev \
    python3~=3.11 python3-dev~=3.11 \
    py3-pip

# Install app code
RUN mkdir /app
ADD ./setup.* README.md /app/
ADD cloudunmap    /app/cloudunmap
ADD tests         /app/tests

# Install app deps
RUN cd /app && pip3 install -e .[dev]

# Run as non-root
RUN adduser app -S -u 1000
USER app

# Switch the cwd to /app so that running app and tests is easier
WORKDIR /app

CMD [ "python3", "-m", "cloudunmap.cli" ]
